package com.ailk.dubbo.model.polling;

import java.io.Serializable;
import java.util.Date;

public class Polling implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = -6340191152363616507L;

	private String sId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PM_SVC_STRATEGY.S_NAME
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    private String sName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PM_SVC_STRATEGY.S_CODE
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    private String sCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PM_SVC_STRATEGY.S_TITLE
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    private String sTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PM_SVC_STRATEGY.S_SCOPE
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    private String sScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PM_SVC_STRATEGY.S_FLAG
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    private String sFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PM_SVC_STRATEGY.S_SORT
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    private Integer sSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PM_SVC_STRATEGY.S_STYLE
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    private String sStyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PM_SVC_STRATEGY.INDB_TIME
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    private Date indbTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PM_SVC_STRATEGY.REMARK
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PM_SVC_STRATEGY.S_ID
     *
     * @return the value of PM_SVC_STRATEGY.S_ID
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    public String getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PM_SVC_STRATEGY.S_ID
     *
     * @param sId the value for PM_SVC_STRATEGY.S_ID
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    public void setsId(String sId) {
        this.sId = sId == null ? null : sId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PM_SVC_STRATEGY.S_NAME
     *
     * @return the value of PM_SVC_STRATEGY.S_NAME
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PM_SVC_STRATEGY.S_NAME
     *
     * @param sName the value for PM_SVC_STRATEGY.S_NAME
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PM_SVC_STRATEGY.S_CODE
     *
     * @return the value of PM_SVC_STRATEGY.S_CODE
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    public String getsCode() {
        return sCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PM_SVC_STRATEGY.S_CODE
     *
     * @param sCode the value for PM_SVC_STRATEGY.S_CODE
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    public void setsCode(String sCode) {
        this.sCode = sCode == null ? null : sCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PM_SVC_STRATEGY.S_TITLE
     *
     * @return the value of PM_SVC_STRATEGY.S_TITLE
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    public String getsTitle() {
        return sTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PM_SVC_STRATEGY.S_TITLE
     *
     * @param sTitle the value for PM_SVC_STRATEGY.S_TITLE
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    public void setsTitle(String sTitle) {
        this.sTitle = sTitle == null ? null : sTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PM_SVC_STRATEGY.S_SCOPE
     *
     * @return the value of PM_SVC_STRATEGY.S_SCOPE
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    public String getsScope() {
        return sScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PM_SVC_STRATEGY.S_SCOPE
     *
     * @param sScope the value for PM_SVC_STRATEGY.S_SCOPE
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    public void setsScope(String sScope) {
        this.sScope = sScope == null ? null : sScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PM_SVC_STRATEGY.S_FLAG
     *
     * @return the value of PM_SVC_STRATEGY.S_FLAG
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    public String getsFlag() {
        return sFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PM_SVC_STRATEGY.S_FLAG
     *
     * @param sFlag the value for PM_SVC_STRATEGY.S_FLAG
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    public void setsFlag(String sFlag) {
        this.sFlag = sFlag == null ? null : sFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PM_SVC_STRATEGY.S_SORT
     *
     * @return the value of PM_SVC_STRATEGY.S_SORT
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    public Integer getsSort() {
        return sSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PM_SVC_STRATEGY.S_SORT
     *
     * @param sSort the value for PM_SVC_STRATEGY.S_SORT
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    public void setsSort(Integer sSort) {
        this.sSort = sSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PM_SVC_STRATEGY.S_STYLE
     *
     * @return the value of PM_SVC_STRATEGY.S_STYLE
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    public String getsStyle() {
        return sStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PM_SVC_STRATEGY.S_STYLE
     *
     * @param sStyle the value for PM_SVC_STRATEGY.S_STYLE
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    public void setsStyle(String sStyle) {
        this.sStyle = sStyle == null ? null : sStyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PM_SVC_STRATEGY.INDB_TIME
     *
     * @return the value of PM_SVC_STRATEGY.INDB_TIME
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    public Date getIndbTime() {
        return indbTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PM_SVC_STRATEGY.INDB_TIME
     *
     * @param indbTime the value for PM_SVC_STRATEGY.INDB_TIME
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    public void setIndbTime(Date indbTime) {
        this.indbTime = indbTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PM_SVC_STRATEGY.REMARK
     *
     * @return the value of PM_SVC_STRATEGY.REMARK
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PM_SVC_STRATEGY.REMARK
     *
     * @param remark the value for PM_SVC_STRATEGY.REMARK
     *
     * @mbggenerated Wed Nov 12 15:12:22 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}